# Site settings
title: Ion
email: karmicdataconsulting@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Karmic Data, a blog focused on the advanced analysis of data. 
 I break down and explain advanced concepts in data science, machine learning, and AI.
 Also using data to illustrate and tell stories.
baseurl: "/Ion-Jekyll-Theme" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
